const express = require('express')
const app = express()
const path = require('path')
const mongoose = require('mongoose')
app.use(express.urlencoded({extended:false}))
mongoose.connect('mongodb://localhost:27017/blogify').then(()=>console.log('connected to DB'))
const fs = require('fs')
app.set('view engine','ejs')
app.set('views',path.resolve('./views'))
app.use(express.urlencoded({extended:false}))
app.use(express.json())
const userRouter = require("./routes/user")
app.use('/user',userRouter)
app.get('/',(req,res)=>{
    res.render('home')
})
app.listen(5000,()=>{
    console.log('server listening to port : 5000')
})
