const express = require('express')
const app = express()
const path = require('path')
const mongoose = require('mongoose')
const cookieParser = require('cookie-parser')
const checkForAuthCookie = require('./middleware/auth')
app.use(express.static(path.resolve('./public')))
const blog = require('./models/blog')
app.use(cookieParser())
app.use(checkForAuthCookie("uid"))
app.use(express.urlencoded({extended:false}))
mongoose.connect('mongodb://localhost:27017/blogify').then(()=>console.log('connected to DB'))
const fs = require('fs')
app.set('view engine','ejs')
app.set('views',path.resolve('./views'))
app.use(express.urlencoded({extended:false}))
app.use(express.json())
const userRouter = require("./routes/user")
const blogRouter = require('./routes/blog')
const user = require('./models/user')
const { validateToken } = require('./services/auth')
app.use('/blogs',blogRouter)
app.use('/user',userRouter)
app.get('/',async(req,res)=>{
    const blogs = await blog.find({})

    
    console.log(req.user)
    res.render('home',{user:req.user,blogs})
})

app.listen(5000,()=>{
    console.log('server listening to port : 5000')
})
